import {AdditionalActionSourcesService} from './ActionSourcesService/AdditionalActionSourcesService';
import {AdditionalAdmRefreshTokensService} from './AdmRefreshTokensService/AdditionalAdmRefreshTokensService';
import {AdditionalAuditAuthsService} from './AuditAuthsService/AdditionalAuditAuthsService';
import {AdditionalAuditDataExportsService} from './AuditDataExportsService/AdditionalAuditDataExportsService';
import {AdditionalAuditFilesExportsService} from './AuditFilesExportsService/AdditionalAuditFilesExportsService';
import {AdditionalAuditLogActionTypesService} from './AuditLogActionTypesService/AdditionalAuditLogActionTypesService';
import {AdditionalAuditLogsService} from './AuditLogsService/AdditionalAuditLogsService';
import {AdditionalAuditManagersAndPermissionsService} from './AuditManagersAndPermissionsService/AdditionalAuditManagersAndPermissionsService';
import {AdditionalAuditReportsService} from './AuditReportsService/AdditionalAuditReportsService';
import {AdditionalAuthOperationsService} from './AuthOperationsService/AdditionalAuthOperationsService';
import {AdditionalAvailableCarriersForRolesService} from './AvailableCarriersForRolesService/AdditionalAvailableCarriersForRolesService';
import {AdditionalBenefitsService} from './BenefitsService/AdditionalBenefitsService';
import {AdditionalBrandsService} from './BrandsService/AdditionalBrandsService';
import {AdditionalCalculationTypesService} from './CalculationTypesService/AdditionalCalculationTypesService';
import {AdditionalCarTypesService} from './CarTypesService/AdditionalCarTypesService';
import {AdditionalCarriersService} from './CarriersService/AdditionalCarriersService';
import {AdditionalCountriesService} from './CountriesService/AdditionalCountriesService';
import {AdditionalDelegationsService} from './DelegationsService/AdditionalDelegationsService';
import {AdditionalDynamicPassengerTagRulesService} from './DynamicPassengerTagRulesService/AdditionalDynamicPassengerTagRulesService';
import {AdditionalEmailsService} from './EmailsService/AdditionalEmailsService';
import {AdditionalEntitiesService} from './EntitiesService/AdditionalEntitiesService';
import {AdditionalExternalEmailsSearchTrackingsService} from './ExternalEmailsSearchTrackingsService/AdditionalExternalEmailsSearchTrackingsService';
import {AdditionalExternalIdentityDocumentsSearchTrackingsService} from './ExternalIdentityDocumentsSearchTrackingsService/AdditionalExternalIdentityDocumentsSearchTrackingsService';
import {AdditionalExternalPassengersSearchTrackingsService} from './ExternalPassengersSearchTrackingsService/AdditionalExternalPassengersSearchTrackingsService';
import {AdditionalExternalPhonesSearchTrackingsService} from './ExternalPhonesSearchTrackingsService/AdditionalExternalPhonesSearchTrackingsService';
import {AdditionalExternalServiceSalesSearchTrackingsService} from './ExternalServiceSalesSearchTrackingsService/AdditionalExternalServiceSalesSearchTrackingsService';
import {AdditionalExternalSpendingsSearchTrackingsService} from './ExternalSpendingsSearchTrackingsService/AdditionalExternalSpendingsSearchTrackingsService';
import {AdditionalExternalTripsSearchTrackingsService} from './ExternalTripsSearchTrackingsService/AdditionalExternalTripsSearchTrackingsService';
import {AdditionalFederalMembersService} from './FederalMembersService/AdditionalFederalMembersService';
import {AdditionalFilesService} from './FilesService/AdditionalFilesService';
import {AdditionalGendersService} from './GendersService/AdditionalGendersService';
import {AdditionalGlossaryTermsService} from './GlossaryTermsService/AdditionalGlossaryTermsService';
import {AdditionalHealthcareOrMarketingContactsService} from './HealthcareOrMarketingContactsService/AdditionalHealthcareOrMarketingContactsService';
import {AdditionalIdentityDocumentTypesService} from './IdentityDocumentTypesService/AdditionalIdentityDocumentTypesService';
import {AdditionalIdentityDocumentsService} from './IdentityDocumentsService/AdditionalIdentityDocumentsService';
import {AdditionalLanguagesService} from './LanguagesService/AdditionalLanguagesService';
import {AdditionalLinkingPassengersToTServiceSalesService} from './LinkingPassengersToTServiceSalesService/AdditionalLinkingPassengersToTServiceSalesService';
import {AdditionalLinkingPassengersToTripsService} from './LinkingPassengersToTripsService/AdditionalLinkingPassengersToTripsService';
import {AdditionalMailingCampaignStatusesService} from './MailingCampaignStatusesService/AdditionalMailingCampaignStatusesService';
import {AdditionalMailingCampaignsService} from './MailingCampaignsService/AdditionalMailingCampaignsService';
import {AdditionalMailingMessageStatusesService} from './MailingMessageStatusesService/AdditionalMailingMessageStatusesService';
import {AdditionalMailingMessagesService} from './MailingMessagesService/AdditionalMailingMessagesService';
import {AdditionalMailingTypesService} from './MailingTypesService/AdditionalMailingTypesService';
import {AdditionalMainIndustriesService} from './MainIndustriesService/AdditionalMainIndustriesService';
import {AdditionalManagerLoginsService} from './ManagerLoginsService/AdditionalManagerLoginsService';
import {AdditionalManagersService} from './ManagersService/AdditionalManagersService';
import {AdditionalManagersToPermissionsService} from './ManagersToPermissionsService/AdditionalManagersToPermissionsService';
import {AdditionalManagersToRolesService} from './ManagersToRolesService/AdditionalManagersToRolesService';
import {AdditionalMessageFilesService} from './MessageFilesService/AdditionalMessageFilesService';
import {AdditionalMessageTemplateLangVariantsService} from './MessageTemplateLangVariantsService/AdditionalMessageTemplateLangVariantsService';
import {AdditionalMessageTemplatesService} from './MessageTemplatesService/AdditionalMessageTemplatesService';
import {AdditionalMessageTypesService} from './MessageTypesService/AdditionalMessageTypesService';
import {AdditionalMessagesService} from './MessagesService/AdditionalMessagesService';
import {AdditionalNoteFilesService} from './NoteFilesService/AdditionalNoteFilesService';
import {AdditionalNotesService} from './NotesService/AdditionalNotesService';
import {AdditionalOperationTypesService} from './OperationTypesService/AdditionalOperationTypesService';
import {AdditionalOrganizationTypesService} from './OrganizationTypesService/AdditionalOrganizationTypesService';
import {AdditionalOwnershipTypesService} from './OwnershipTypesService/AdditionalOwnershipTypesService';
import {AdditionalPartnerAgreementStatusesService} from './PartnerAgreementStatusesService/AdditionalPartnerAgreementStatusesService';
import {AdditionalPartnerAgreementTypesService} from './PartnerAgreementTypesService/AdditionalPartnerAgreementTypesService';
import {AdditionalPartnerAgreementsService} from './PartnerAgreementsService/AdditionalPartnerAgreementsService';
import {AdditionalPartnerTagRulesService} from './PartnerTagRulesService/AdditionalPartnerTagRulesService';
import {AdditionalPartnerTagsService} from './PartnerTagsService/AdditionalPartnerTagsService';
import {AdditionalPartnersService} from './PartnersService/AdditionalPartnersService';
import {AdditionalPassengerAggregateTrackingsService} from './PassengerAggregateTrackingsService/AdditionalPassengerAggregateTrackingsService';
import {AdditionalPassengerAggregatesService} from './PassengerAggregatesService/AdditionalPassengerAggregatesService';
import {AdditionalPassengerCreateRequestStatusesService} from './PassengerCreateRequestStatusesService/AdditionalPassengerCreateRequestStatusesService';
import {AdditionalPassengerCreateRequestsService} from './PassengerCreateRequestsService/AdditionalPassengerCreateRequestsService';
import {AdditionalPassengerTagRulesService} from './PassengerTagRulesService/AdditionalPassengerTagRulesService';
import {AdditionalPassengerTagsService} from './PassengerTagsService/AdditionalPassengerTagsService';
import {AdditionalPassengersService} from './PassengersService/AdditionalPassengersService';
import {AdditionalPaymentMethodsService} from './PaymentMethodsService/AdditionalPaymentMethodsService';
import {AdditionalPermissionsService} from './PermissionsService/AdditionalPermissionsService';
import {AdditionalPhonesService} from './PhonesService/AdditionalPhonesService';
import {AdditionalReferenceDocumentsService} from './ReferenceDocumentsService/AdditionalReferenceDocumentsService';
import {AdditionalRegistrationSourcesService} from './RegistrationSourcesService/AdditionalRegistrationSourcesService';
import {AdditionalRelationshipTypesService} from './RelationshipTypesService/AdditionalRelationshipTypesService';
import {AdditionalRoadsService} from './RoadsService/AdditionalRoadsService';
import {AdditionalRolesService} from './RolesService/AdditionalRolesService';
import {AdditionalRolesToPermissionsService} from './RolesToPermissionsService/AdditionalRolesToPermissionsService';
import {AdditionalSaleChannelsService} from './SaleChannelsService/AdditionalSaleChannelsService';
import {AdditionalServiceClassesService} from './ServiceClassesService/AdditionalServiceClassesService';
import {AdditionalServiceCostsService} from './ServiceCostsService/AdditionalServiceCostsService';
import {AdditionalServiceSalesService} from './ServiceSalesService/AdditionalServiceSalesService';
import {AdditionalServiceTagRulesService} from './ServiceTagRulesService/AdditionalServiceTagRulesService';
import {AdditionalServiceTagsService} from './ServiceTagsService/AdditionalServiceTagsService';
import {AdditionalServiceTypesService} from './ServiceTypesService/AdditionalServiceTypesService';
import {AdditionalServicesService} from './ServicesService/AdditionalServicesService';
import {AdditionalSetPasswordRequestsService} from './SetPasswordRequestsService/AdditionalSetPasswordRequestsService';
import {AdditionalSpendingsService} from './SpendingsService/AdditionalSpendingsService';
import {AdditionalStationsService} from './StationsService/AdditionalStationsService';
import {AdditionalStatsService} from './StatsService/AdditionalStatsService';
import {AdditionalSubAgentsService} from './SubAgentsService/AdditionalSubAgentsService';
import {AdditionalSupportTicketStatusesService} from './SupportTicketStatusesService/AdditionalSupportTicketStatusesService';
import {AdditionalSupportTicketTypesService} from './SupportTicketTypesService/AdditionalSupportTicketTypesService';
import {AdditionalSupportTicketsService} from './SupportTicketsService/AdditionalSupportTicketsService';
import {AdditionalTagsToPartnersService} from './TagsToPartnersService/AdditionalTagsToPartnersService';
import {AdditionalTagsToPassengersService} from './TagsToPassengersService/AdditionalTagsToPassengersService';
import {AdditionalTagsToServicesService} from './TagsToServicesService/AdditionalTagsToServicesService';
import {AdditionalTemplateStylesService} from './TemplateStylesService/AdditionalTemplateStylesService';
import {AdditionalThreadsService} from './ThreadsService/AdditionalThreadsService';
import {AdditionalTicketTypesService} from './TicketTypesService/AdditionalTicketTypesService';
import {AdditionalTrainCategoriesService} from './TrainCategoriesService/AdditionalTrainCategoriesService';
import {AdditionalTrainTypesService} from './TrainTypesService/AdditionalTrainTypesService';
import {AdditionalTransactionTypesService} from './TransactionTypesService/AdditionalTransactionTypesService';
import {AdditionalTripTypesService} from './TripTypesService/AdditionalTripTypesService';
import {AdditionalTripsService} from './TripsService/AdditionalTripsService';
import {AdditionalTxToPassengerLinkingRuleSetsService} from './TxToPassengerLinkingRuleSetsService/AdditionalTxToPassengerLinkingRuleSetsService';
import {AdditionalUnitsService} from './UnitsService/AdditionalUnitsService';
import {AdditionalVidpasesService} from './VidpasesService/AdditionalVidpasesService';
import {HelpService} from './HelpService/HelpService';

// DO NOT EDIT! THIS IS GENERATED FILE

export interface BaseServices {
  help: HelpService;
  actionSources: AdditionalActionSourcesService;
  admRefreshTokens: AdditionalAdmRefreshTokensService;
  auditAuths: AdditionalAuditAuthsService;
  auditDataExports: AdditionalAuditDataExportsService;
  auditFilesExports: AdditionalAuditFilesExportsService;
  auditLogActionTypes: AdditionalAuditLogActionTypesService;
  auditLogs: AdditionalAuditLogsService;
  auditManagersAndPermissions: AdditionalAuditManagersAndPermissionsService;
  auditReports: AdditionalAuditReportsService;
  authOperations: AdditionalAuthOperationsService;
  availableCarriersForRoles: AdditionalAvailableCarriersForRolesService;
  benefits: AdditionalBenefitsService;
  brands: AdditionalBrandsService;
  calculationTypes: AdditionalCalculationTypesService;
  carTypes: AdditionalCarTypesService;
  carriers: AdditionalCarriersService;
  countries: AdditionalCountriesService;
  delegations: AdditionalDelegationsService;
  dynamicPassengerTagRules: AdditionalDynamicPassengerTagRulesService;
  emails: AdditionalEmailsService;
  entities: AdditionalEntitiesService;
  externalEmailsSearchTrackings: AdditionalExternalEmailsSearchTrackingsService;
  externalIdentityDocumentsSearchTrackings: AdditionalExternalIdentityDocumentsSearchTrackingsService;
  externalPassengersSearchTrackings: AdditionalExternalPassengersSearchTrackingsService;
  externalPhonesSearchTrackings: AdditionalExternalPhonesSearchTrackingsService;
  externalServiceSalesSearchTrackings: AdditionalExternalServiceSalesSearchTrackingsService;
  externalSpendingsSearchTrackings: AdditionalExternalSpendingsSearchTrackingsService;
  externalTripsSearchTrackings: AdditionalExternalTripsSearchTrackingsService;
  federalMembers: AdditionalFederalMembersService;
  files: AdditionalFilesService;
  genders: AdditionalGendersService;
  glossaryTerms: AdditionalGlossaryTermsService;
  healthcareOrMarketingContacts: AdditionalHealthcareOrMarketingContactsService;
  identityDocumentTypes: AdditionalIdentityDocumentTypesService;
  identityDocuments: AdditionalIdentityDocumentsService;
  languages: AdditionalLanguagesService;
  linkingPassengersToTServiceSales: AdditionalLinkingPassengersToTServiceSalesService;
  linkingPassengersToTrips: AdditionalLinkingPassengersToTripsService;
  mailingCampaignStatuses: AdditionalMailingCampaignStatusesService;
  mailingCampaigns: AdditionalMailingCampaignsService;
  mailingMessageStatuses: AdditionalMailingMessageStatusesService;
  mailingMessages: AdditionalMailingMessagesService;
  mailingTypes: AdditionalMailingTypesService;
  mainIndustries: AdditionalMainIndustriesService;
  managerLogins: AdditionalManagerLoginsService;
  managers: AdditionalManagersService;
  managersToPermissions: AdditionalManagersToPermissionsService;
  managersToRoles: AdditionalManagersToRolesService;
  messageFiles: AdditionalMessageFilesService;
  messageTemplateLangVariants: AdditionalMessageTemplateLangVariantsService;
  messageTemplates: AdditionalMessageTemplatesService;
  messageTypes: AdditionalMessageTypesService;
  messages: AdditionalMessagesService;
  noteFiles: AdditionalNoteFilesService;
  notes: AdditionalNotesService;
  operationTypes: AdditionalOperationTypesService;
  organizationTypes: AdditionalOrganizationTypesService;
  ownershipTypes: AdditionalOwnershipTypesService;
  partnerAgreementStatuses: AdditionalPartnerAgreementStatusesService;
  partnerAgreementTypes: AdditionalPartnerAgreementTypesService;
  partnerAgreements: AdditionalPartnerAgreementsService;
  partnerTagRules: AdditionalPartnerTagRulesService;
  partnerTags: AdditionalPartnerTagsService;
  partners: AdditionalPartnersService;
  passengerAggregateTrackings: AdditionalPassengerAggregateTrackingsService;
  passengerAggregates: AdditionalPassengerAggregatesService;
  passengerCreateRequestStatuses: AdditionalPassengerCreateRequestStatusesService;
  passengerCreateRequests: AdditionalPassengerCreateRequestsService;
  passengerTagRules: AdditionalPassengerTagRulesService;
  passengerTags: AdditionalPassengerTagsService;
  passengers: AdditionalPassengersService;
  paymentMethods: AdditionalPaymentMethodsService;
  permissions: AdditionalPermissionsService;
  phones: AdditionalPhonesService;
  referenceDocuments: AdditionalReferenceDocumentsService;
  registrationSources: AdditionalRegistrationSourcesService;
  relationshipTypes: AdditionalRelationshipTypesService;
  roads: AdditionalRoadsService;
  roles: AdditionalRolesService;
  rolesToPermissions: AdditionalRolesToPermissionsService;
  saleChannels: AdditionalSaleChannelsService;
  serviceClasses: AdditionalServiceClassesService;
  serviceCosts: AdditionalServiceCostsService;
  serviceSales: AdditionalServiceSalesService;
  serviceTagRules: AdditionalServiceTagRulesService;
  serviceTags: AdditionalServiceTagsService;
  serviceTypes: AdditionalServiceTypesService;
  services: AdditionalServicesService;
  setPasswordRequests: AdditionalSetPasswordRequestsService;
  spendings: AdditionalSpendingsService;
  stations: AdditionalStationsService;
  stats: AdditionalStatsService;
  subAgents: AdditionalSubAgentsService;
  supportTicketStatuses: AdditionalSupportTicketStatusesService;
  supportTicketTypes: AdditionalSupportTicketTypesService;
  supportTickets: AdditionalSupportTicketsService;
  tagsToPartners: AdditionalTagsToPartnersService;
  tagsToPassengers: AdditionalTagsToPassengersService;
  tagsToServices: AdditionalTagsToServicesService;
  templateStyles: AdditionalTemplateStylesService;
  threads: AdditionalThreadsService;
  ticketTypes: AdditionalTicketTypesService;
  trainCategories: AdditionalTrainCategoriesService;
  trainTypes: AdditionalTrainTypesService;
  transactionTypes: AdditionalTransactionTypesService;
  tripTypes: AdditionalTripTypesService;
  trips: AdditionalTripsService;
  txToPassengerLinkingRuleSets: AdditionalTxToPassengerLinkingRuleSetsService;
  units: AdditionalUnitsService;
  vidpases: AdditionalVidpasesService;
}
